default: &default
  adapter: postgresql
  pool: 5
  host: localhost
  username: postgres
  password: postgres
  encoding: unicode
  template: template0


development:
  <<: *default
  database: seniorsafeguard

 

test:
  <<: *default
  database: seniorsafeguard_test

  
  
production:
  <<: *default
  database: seniorsafeguard_production